AWSTemplateFormatVersion: "2010-09-09"
Description: ""

Parameters:
  ParentS3Stack:
    Description: 'Stack name of parent S3 stack based on s3-bucket.yaml template.'
    Type: String
  ParentKmsKeyStack:
    Description: 'Optional Stack name of parent KMS key stack based on security/kms-key.yaml template (works with certain instance types https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-instance-types.html only).'
    Type: String
    Default: ''

Conditions:
  HasKmsKey: !Not [!Equals [!Ref ParentKmsKeyStack, '']]

Resources:
  CloudTrail:
    Type: "AWS::CloudTrail::Trail"
    Properties:
      TrailName: "GlobalCloudTrail"
      IsLogging: true
      EnableLogFileValidation: true
      EventSelectors:
        - IncludeManagementEvents: true
          ReadWriteType: "All"
        - DataResources:
            - Type: "AWS::S3::Object"
              Values:
                - "arn:aws:s3:::"
            - Type: "AWS::Lambda::Function"
              Values:
                - "arn:aws:lambda"
            - Type: "AWS::DynamoDB::Table"
              Values:
                - "arn:aws:dynamodb"
          ReadWriteType: "All"
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      S3BucketName: {'Fn::ImportValue': !Sub '${ParentS3Stack}-BucketName'}
      CloudWatchLogsLogGroupArn:
        Fn::GetAtt:
          - "CloudWatchLogGroupCloudTrail"
          - "Arn"
      CloudWatchLogsRoleArn:
        Fn::GetAtt:
          - "IamRoleForCwLogsCloudTrail"
          - "Arn"
      KMSKeyId: !If [HasKmsKey, {Enabled: true, KmsKeyId: {'Fn::ImportValue': !Sub '${ParentKmsKeyStack}-KeyId'}}, !Ref 'AWS::NoValue']

  CloudWatchLogGroupCloudTrail:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "CloudTrailLogs"

  IamRoleForCwLogsCloudTrail:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "allow-access-to-cw-logs"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
      RoleName: "CTtoCW"